### ISSUE TITLE
Type initialiser for SchemaRegistry throws an exception

### ISSUE THREAD

**Issue by wazzamatazz** [gregsdennis/json-everything#138]
**Environment**
- Nuget Package: JsonSchema.Net
- Nuget Version: 1.10.5
- OS: Windows 10
- .Net Target: .NET Core 3.1.16, .NET 5.0.7

**Describe the bug**
An exception is thrown by the type initialiser for `ValidationOptions` that is caused by a `NullReferenceException` in the `SchemaRegistry` type initialiser:

```
System.TypeInitializationException: The type initializer for 'Json.Schema.ValidationOptions' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'Json.Schema.SchemaRegistry' threw an exception.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Json.Schema.JsonSchema.RegisterSubschemasAndGetBaseUri(SchemaRegistry registry, Uri currentUri)
   at Json.Schema.ItemsKeyword.Json.Schema.IRefResolvable.RegisterSubschemas(SchemaRegistry registry, Uri currentUri)
   at Json.Schema.JsonSchema.RegisterSubschemasAndGetBaseUri(SchemaRegistry registry, Uri currentUri)
   at Json.Schema.DefinitionsKeyword.Json.Schema.IRefResolvable.RegisterSubschemas(SchemaRegistry registry, Uri currentUri)
   at Json.Schema.JsonSchema.RegisterSubschemasAndGetBaseUri(SchemaRegistry registry, Uri currentUri)
   at Json.Schema.JsonSchema.RegisterSubschemas(SchemaRegistry registry, Uri currentUri)
   at Json.Schema.SchemaRegistry..cctor()
   --- End of inner exception stack trace ---
   at Json.Schema.SchemaRegistry..ctor(ValidationOptions options)
   at Json.Schema.ValidationOptions..ctor()
   at Json.Schema.ValidationOptions..cctor()
   --- End of inner exception stack trace ---
   at Json.Schema.ValidationOptions.get_Default()
```

The issue means that it is not possible to validate a `JsonElement` against a schema.

**To Reproduce**
```csharp
try {
    var options = Json.Schema.ValidationOptions.Default;
}
catch (Exception e) {
    Console.WriteLine(e.ToString());
}
```

**Expected behavior**
The type initialiser for `SchemaRegistry` should not throw a `NullReferenceException`.

**Comment by wazzamatazz** [comment]
Issue specifically seems to be [this line](https://github.com/gregsdennis/json-everything/blob/b8b5ccd24c47615ea36c16154cab9c8ceb20789a/JsonSchema/SchemaRegistry.cs#L52):

```csharp
internal Draft ValidatingAs => _options.ValidatingAs;
```

Presumably, the compiler is converting the property declaration into something like this under the hood:

```csharp
internal Draft ValidatingAs { get; } = _options.ValidatingAs;
```

However, since `_options` doesn't get set until the constructor, it will be `null` when the property value is set, since this will happen before the constructor runs.

An appropriate fix could be to either set the property value in the constructor instead, or if you want it to always reflect the current `_options.ValidatingAs` value, change it to:

```csharp
internal Draft ValidatingAs {
  get { return _options?.ValidatingAs ?? Draft.Unspecified; }
}
```

**Comment by gregsdennis** [comment]
That behavior needs to be verified before changing any code on this assumption.  Making that change would be an inappropriate optimization by the compiler, and I've never seen it do something like that.

Have you stepped through the code to see what happens?

Let me dig in a bit and find the culprit.  I want to know how `_options` is null.

**Comment by wazzamatazz** [comment]
When I step through the code, the error occurs before the `SchemaRegistry` constructor runs, so I'm sure that it's because of the property declaration syntax.

**Comment by wazzamatazz** [comment]
When I step through the error occurs before the `SchemaRegistry` constructor is called so I had assumed that it was early evaluation of the property initialiser, but I think you're correct that it's not that, because I can't recreate the same behaviour with a simple test classes.

**Comment by wazzamatazz** [comment]
I think it's related to the fact that when `ValidationOptions.Default` is created, the (instance) constructor makes a call to create a new `SchemaRegistry`, and the static constructor for `SchemaRegistry` then attempts to set its `Global` property using `ValidationOptions.Default` as a parameter before the constructor that is initialising `ValidationOptions.Default` has finished running. This would mean that the value `ValidationOptions.Default` in the static `SchemaRegistry` constructor would still be null at that time.

I can recreate the same behaviour with the following example:

```csharp
void Main() {
    var x = TestClass1.Default;
}

public static void PrintValue(TestClass2 obj) {
    Console.WriteLine(obj.Value);
}

public class TestClass1 {

    private readonly TestClass2 _testClass2;

    public static TestClass1 Default { get; } = new TestClass1();

    public int Value { get; }

    public TestClass1() {
        _testClass2 = new TestClass2(this);
    }
    
}

public class TestClass2 {

    private readonly TestClass1 _testClass1;
    
    public int Value => _testClass1.Value;

    public static TestClass2 Default { get; }

    static TestClass2() {
        Default = new TestClass2(TestClass1.Default);
        // Remove this call and no error occurs!
        PrintValue(Default);
    }

    public TestClass2(TestClass1 testClass1) {
        _testClass1 = testClass1;
    }
    
}
```

**Comment by cbdabner** [comment]
I haven't looked into the library code at all, but would agree it's around the static construction.

When doing this, the exception is thrown:
```c#
var validationResults = schema.Validate(payload, new() {});
```

However, when doing this, the code runs successfully:
```c#
ValidationOptions options = new() {};
var validationResults = schema.Validate(payload, options);
```

**Comment by gregsdennis** [comment]
Yeah, something is definitely off there.

```c#
// in ValidationOptions
static ValidationOptions Default = new ValidationOptions();

public ValidationOptions()
{
    Registry = new SchemaRegistry(this);
}

// in SchemaRegistry
static SchemaRegistry()
{
    Global = new SchemaRegistry(ValidationOptions.Default);
}
```

So...

1. `ValidationOptions.Default` is initialized when the class is referenced.  This creates a new instance, which begins the process to create a new `SchemaRegistry`.
2. But the `SchemaRegistry` class must be initialized first, so it calls the static constructor, which references ValidationOptions.Default, which is null at this point.  // this is it

Regardless, I have a circular reference here.  I did this just so I could have the `ValidatingAs` on the registry because I need it to determine the behavior of `$ref` which changes slightly after draft 7 while `JsonSchema` is find and registering subschemas.

I'll work out a better way for this and have an update soon.  Thanks for the input.

**Comment by wazzamatazz** [comment]
Yeah, that's my understanding of the situation. Will close the PR I created around this as it's no longer relevant.

**Comment by gregsdennis** [comment]
Okay.  Please have a look at ☝️.

**Comment by wazzamatazz** [comment]
Looks good to me 👍

**Comment by yohny** [comment]
was this trully fixed? I have just tired v1.10.6 and got the exception when trying to validate json:
```
System.TypeInitializationException
  HResult=0x80131534
  Message=The type initializer for 'Json.Schema.ValidationOptions' threw an exception.
  Source=JsonSchema.Net
  StackTrace:
   at Json.Schema.ValidationOptions.get_Default()
   at Json.Schema.JsonSchema.ToDebugString()

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
TypeInitializationException: The type initializer for 'Json.Schema.SchemaRegistry' threw an exception.

Inner Exception 2:
NullReferenceException: Object reference not set to an instance of an object.
```

my code:
```csharp
var schema = JsonSchema.FromText(schemaString);
var jsonDoc = JsonDocument.Parse(bodyString);
var validationResult = schema.Validate(jsonDoc.RootElement); // here the exception is thrown
```

**Comment by gregsdennis** [comment]
My test code is doing what you put, @yohny.  Do you think you can write a test case that reproduces the error?

**Comment by yohny** [comment]
my test case is pretty  much the  lines that I wrote, I just read the schema from an embedded json file before that. It also happens if validated json string is just an empty object `"{}"`. I'm runnig on .NET 5  with C# 9.
Here is the complete code sample:

```csharp
static void Main(string[] args)
{
    using var sr = new StreamReader(Assembly.GetExecutingAssembly().GetManifestResourceStream("JsonSchemaRepro.schema.json"));
    var schemaString = sr.ReadToEnd();

    var schema = JsonSchema.FromText(schemaString);
    var jsonDoc = JsonDocument.Parse("{}");
    var validationResult = schema.Validate(jsonDoc.RootElement); // here the exception is thrown
}
```

the schema.json content:
```json
{
  "$schema": "https://json-schema.org/draft/2019-09/schema",
  "title": "Receiver schema for pia-shopdb-pub",
  "type": "object",
  "required": [
    "eventType",
    "timestamp",
    "eventId",
    "publisherId",
    "NotifyPartnerDetails"
  ],
  "properties": {
    "eventId": {
      "type": "string"
    },
    "publisherId": {
      "type": "string"
    },
    "NotifyPartnerDetails": {
      "minItems": 0,
      "type": "object",
      "properties": {
        "AdditionalInformation": {
          "type": "object",
          "properties": {
            "Language": {
              "type": "string"
            },
            "Remark": {
              "type": "string"
            }
          }
        },
        "Skills": {
          "type": "object",
          "properties": {
            "SelfinstalledAllowed": {
              "description": "0 - false, 1 - true",
              "type": "string"
            },
            "BasedRetailerInstallation": {
              "type": "string"
            }
          }
        },
        "POBoxAddress": {
          "type": "object",
          "properties": {
            "uniqueAddressIdGAIA": {
              "type": "string"
            },
            "POBox": {
              "type": "string"
            },
            "Country": {
              "type": "string"
            },
            "positionGAIA": {
              "type": "string"
            },
            "City": {
              "type": "string"
            },
            "PLZ": {
              "type": "string"
            }
          }
        },
        "Channel": {
          "type": "object",
          "properties": {
            "Subkanal": {
              "type": "string"
            },
            "SubkanalId": {
              "type": "string"
            },
            "OwnThird": {
              "type": "string"
            },
            "HauptkanalId": {
              "type": "string"
            },
            "OMSRating": {
              "type": "string"
            },
            "SMERegion": {
              "type": "string"
            },
            "SMESubregion": {
              "type": "string"
            },
            "OptPBX": {
              "type": "string"
            },
            "RatingCategoryId": {
              "type": "string"
            },
            "RatingTypeId": {
              "type": "string"
            },
            "Hauptkanal": {
              "type": "string"
            },
            "LevelUp": {
              "type": "string"
            }
          }
        },
        "LeadManagementInformation": {
          "type": "object",
          "properties": {
            "LeadManagementAllowed": {
              "description": "0 - false, 1 - true",
              "type": "string"
            },
            "LeadManagementEmail": {
              "type": "string"
            }
          }
        },
        "LocationAddress": {
          "type": "object",
          "properties": {
            "uniqueAddressIdGAIA": {
              "type": "string"
            },
            "HouseNumber": {
              "type": "string"
            },
            "Coordinates": {
              "type": "object",
              "properties": {
                "Latitude": {
                  "type": "string"
                },
                "Longitude": {
                  "type": "string"
                }
              }
            },
            "Street": {
              "type": "string"
            },
            "positionGAIA": {
              "type": "string"
            },
            "City": {
              "type": "string"
            },
            "PLZ": {
              "type": "string"
            }
          }
        },
        "Routing": {
          "type": "integer"
        },
        "AccountManager": {
          "type": "object",
          "properties": {
            "Active": {
              "description": "0 - false, 1 - true",
              "type": "string"
            },
            "Nachname": {
              "type": "string"
            },
            "Mobilephone": {
              "type": "string"
            },
            "Geschlecht": {
              "type": "string"
            },
            "Sprache": {
              "type": "string"
            },
            "Vorname": {
              "type": "string"
            }
          }
        },
        "Identifiers": {
          "type": "object",
          "properties": {
            "Partner_ID": {
              "type": "string"
            },
            "EEV_Nbr": {
              "type": "string"
            },
            "BrokerID": {
              "type": "string"
            },
            "VAT_Nbr": {
              "type": "string"
            },
            "SalesOffice": {
              "type": "string"
            },
            "PointOfSaleID": {
              "type": "string"
            },
            "HoldingNbr": {
              "type": "string"
            },
            "DealerId": {
              "type": "string"
            },
            "KreditorNumber": {
              "type": "string"
            },
            "SCN_ENT": {
              "type": "string"
            },
            "Account_payable_nbr": {
              "type": "integer"
            },
            "BankType": {
              "type": "string"
            },
            "Internal_ID": {
              "type": "integer"
            },
            "Mandant": {
              "type": "string"
            },
            "SCN": {
              "type": "string"
            }
          }
        },
        "ValidityInformation": {
          "type": "object",
          "properties": {
            "ValidTo": {
              "format": "date",
              "description": "Format yyyy-MM-ddThh:mm:ss",
              "type": "string"
            },
            "active": {
              "description": "0 - false, 1 - true",
              "type": "string"
            },
            "ValidFrom": {
              "format": "date",
              "description": "Format yyyy-MM-ddThh:mm:ss",
              "type": "string"
            },
            "AddressChangeDate": {
              "format": "date",
              "description": "Format yyyy-MM-dd",
              "type": "string"
            }
          }
        },
        "Contact": {
          "type": "object",
          "properties": {
            "Web": {
              "type": "string"
            },
            "Phone": {
              "type": "string"
            },
            "Fax": {
              "type": "string"
            },
            "eMail": {
              "type": "string"
            }
          }
        },
        "Name": {
          "type": "object",
          "properties": {
            "Name1": {
              "type": "string"
            },
            "Name2": {
              "type": "string"
            }
          }
        }
      }
    },
    "eventType": {
      "type": "string"
    },
    "timestamp": {
      "format": "date-time",
      "type": "string"
    }
  }
}

```

**Comment by gregsdennis** [comment]
Looks like there might be some issues specifically with .Net 5.  I'm updating all of the test projects to run both Core 3.1 and 5.0.

**Comment by gregsdennis** [comment]
Nope.  Scratch that.  All of the schema tests (including this one) runs fine.  (I had a local change that made a few other tests fail, but reverting that change cleared up the tests.)  Here's my new test:

https://github.com/gregsdennis/json-everything/blob/net5-problems/JsonSchema.Tests/GithubTests.cs#L503-L515

Just to be sure the test runner wasn't doing things to stabilize the registry, I created a console app for .net 5 and installed the current version of JsonSchema.Net (1.10.6).  This is the whole program:

```c#
using System;
using System.IO;
using System.Text.Encodings.Web;
using System.Text.Json;
using Json.Schema;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            using var sr = new StreamReader(Assembly.GetExecutingAssembly().GetManifestResourceStream("ConsoleApp1.issue138.json"));
            var schemaString = sr.ReadToEnd();

            var schema = JsonSchema.FromText(schemaString);
            var jsonStr = @"{}";
            var json = JsonDocument.Parse(jsonStr).RootElement;
            var validation = schema.Validate(json, new ValidationOptions { OutputFormat = OutputFormat.Detailed });

            Console.WriteLine(JsonSerializer.Serialize(validation, new JsonSerializerOptions
            {
                WriteIndented = true,
                Encoder = JavaScriptEncoder.UnsafeRelaxedJsonEscaping
            }));
        }
    }
}
```

and the output:

```json
{
  "valid": false,
  "keywordLocation": "#/required",
  "instanceLocation": "#",
  "error": "Required properties [eventType, timestamp, eventId, publisherId, NotifyPartnerDetails] were not present"
}
```

**Comment by yohny** [comment]
if I pass `ValidationOptions` as second argument to `.Validate(..)` it works without exception, but with only one argument the `.Validate(..)` method throws the mentioned exception

**Comment by gregsdennis** [comment]
That did it.  Will work on it.  Thanks.

**Comment by gregsdennis** [comment]
1.10.7 incoming!
