### ISSUE TITLE
Schema Gen 2.10 introduced this exception

### ISSUE THREAD

**Issue by kampilan** [gregsdennis/json-everything#274]
**Environment**
- Nuget Package: JsonSchema.Net.Generation
- Nuget Version: 2.10 and above
- OS: Window 10 and 2019
- .Net Target: Core 6.0

I started getting this Exception when I upgraded to 2.10. It still occurs in 2.20

I reverted to 2.0.1 and it worked fine.

I have included a snippet from the class where the exception originates and the Type it is using to build the schema

Thanks
Jim

System.TypeInitializationException : The type initializer for 'Fabrica.One.Plan.JsonPlanFactory' threw an exception.
  ----> System.ArgumentException : An item with the same key has already been added. Key: Item
   at Fabrica.One.Plan.JsonPlanFactory..ctor(String repositoryRoot, String installationRoot) in E:\repository\fabrica\Fabrica.One.Core\Plan\JsonPlanFactory.cs:line 57
   at Fabrica.One.Core.Tests.BaseOneTest.GetFactory() in E:\repository\fabrica\Fabrica.One.Core.Tests\BaseOneTest.cs:line 524
   at Fabrica.One.Core.Tests.ApplianceTests.Test0700_Appliance_Should_Start() in E:\repository\fabrica\Fabrica.One.Core.Tests\ApplianceTests.cs:line 19
   at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.GetResult()
   at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
   at NUnit.Framework.Internal.Execution.SimpleWorkItem.<>c__DisplayClass4_0.<PerformWork>b__0()
   at NUnit.Framework.Internal.ContextUtils.<>c__DisplayClass1_0`1.<DoIsolated>b__0(Object _)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at NUnit.Framework.Internal.ContextUtils.DoIsolated(ContextCallback callback, Object state)
   at NUnit.Framework.Internal.ContextUtils.DoIsolated[T](Func`1 func)
   at NUnit.Framework.Internal.Execution.SimpleWorkItem.PerformWork()
--ArgumentException
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at Json.Schema.Generation.Generators.ObjectSchemaGenerator.AddConstraints(SchemaGenerationContextBase context)
   at Json.Schema.Generation.SchemaGenerationContextBase.GenerateIntents()
   at Json.Schema.Generation.SchemaGenerationContextCache.Get(Type type, List`1 memberAttributes)
   at Json.Schema.Generation.Generators.ObjectSchemaGenerator.AddConstraints(SchemaGenerationContextBase context)
   at Json.Schema.Generation.SchemaGenerationContextBase.GenerateIntents()
   at Json.Schema.Generation.SchemaGenerationContextCache.Get(Type type, List`1 memberAttributes)
   at Json.Schema.Generation.Generators.ObjectSchemaGenerator.AddConstraints(SchemaGenerationContextBase context)
   at Json.Schema.Generation.SchemaGenerationContextBase.GenerateIntents()
   at Json.Schema.Generation.SchemaGenerationContextCache.Get(Type type, List`1 memberAttributes)
   at Json.Schema.Generation.SchemaGenerationContextCache.Get(Type type, List`1 memberAttributes)
   at Json.Schema.Generation.Generators.ObjectSchemaGenerator.AddConstraints(SchemaGenerationContextBase context)
   at Json.Schema.Generation.SchemaGenerationContextBase.GenerateIntents()
   at Json.Schema.Generation.SchemaGenerationContextCache.Get(Type type, List`1 memberAttributes)
   at Json.Schema.Generation.Generators.ArraySchemaGenerator.AddConstraints(SchemaGenerationContextBase context)
   at Json.Schema.Generation.SchemaGenerationContextBase.GenerateIntents()
   at Json.Schema.Generation.SchemaGenerationContextCache.Get(Type type, List`1 memberAttributes)
   at Json.Schema.Generation.SchemaGenerationContextCache.Get(Type type, List`1 memberAttributes)
   at Json.Schema.Generation.Generators.ObjectSchemaGenerator.AddConstraints(SchemaGenerationContextBase context)
   at Json.Schema.Generation.SchemaGenerationContextBase.GenerateIntents()
   at Json.Schema.Generation.SchemaGenerationContextCache.Get(Type type, List`1 memberAttributes)
   at Json.Schema.Generation.Generators.ArraySchemaGenerator.AddConstraints(SchemaGenerationContextBase context)
   at Json.Schema.Generation.SchemaGenerationContextBase.GenerateIntents()
   at Json.Schema.Generation.SchemaGenerationContextCache.Get(Type type, List`1 memberAttributes)
   at Json.Schema.Generation.SchemaGenerationContextCache.Get(Type type, List`1 memberAttributes)
   at Json.Schema.Generation.Generators.ObjectSchemaGenerator.AddConstraints(SchemaGenerationContextBase context)
   at Json.Schema.Generation.SchemaGenerationContextBase.GenerateIntents()
   at Json.Schema.Generation.SchemaGenerationContextCache.Get(Type type, List`1 memberAttributes)
   at Json.Schema.Generation.JsonSchemaBuilderExtensions.FromType(JsonSchemaBuilder builder, Type type, SchemaGeneratorConfiguration configuration)
   at Json.Schema.Generation.JsonSchemaBuilderExtensions.FromType[T](JsonSchemaBuilder builder, SchemaGeneratorConfiguration configuration)
   at Fabrica.One.Plan.JsonPlanFactory..cctor() in E:\repository\fabrica\Fabrica.One.Core\Plan\JsonPlanFactory.cs:line 47

    public class JsonPlanFactory: IPlanFactory
    {

        private class JsonObjectRefiner : ISchemaRefiner
        {
            public bool ShouldRun(SchemaGenerationContextBase context)
            {
                return context.Type == typeof(JsonObject);
            }

            public void Run(SchemaGenerationContextBase context)
            {
                var intent = context.Intents.FirstOrDefault();
                if( intent is TypeIntent ti )
                    ti.Type = SchemaValueType.Object;
            }
        }

        static JsonPlanFactory()
        {

            var config = new SchemaGeneratorConfiguration();
            config.Refiners.Add(new JsonObjectRefiner());

            var builder = new JsonSchemaBuilder();

**********************************************************
Offending line 47 mentioned int the stack trace above
**********************************************************

            builder.FromType<PlanImpl>(config);

*********************************************************

            PlanSchema = builder.Build();
            SchemaJson = PlanSchema.ToJsonDocument(new JsonSerializerOptions{WriteIndented = true}).RootElement.GetRawText();

        }

        private static JsonSchema PlanSchema { get; }
        private static string SchemaJson { get; }

}

    public class PlanImpl : IPlan
    {

        [Required]
        public string Name { get; set; } = "";

        [Required]
        public string Environment { get; set; } = "";

        [Required]
        [MinLength(0)]
        public string RepositoryVersion { get; set; } = "";

        [Required]
        public bool DeployAppliances { get; set; }

        [Required]
        public bool StartAppliances { get; set; }

        [Required]
        public bool StartInParallel { get; set; }

        [Required]
        public bool AllAppliancesMustDeploy { get; set; }

        [Required]
        [Minimum(10)]
        [Maximum(30)]
        public int WaitForDeploySeconds { get; set; }

        [Required]
        [Minimum(10)]
        [Maximum(240)]
        public int WaitForStartSeconds { get; set; }

        [Required]
        [Minimum(10)]
        [Maximum(240)]
        public int WaitForStopSeconds { get; set; }

        [Required]
        [MinItems(1)]
        public List<DeploymentUnit> Deployments { get; set; } = new List<DeploymentUnit>();

        [JsonIgnore]
        public string RepositoryRoot { get; set; } = "";

        [JsonIgnore]
        public string InstallationRoot { get; set; } = "";

        public void SetRepositoryVersion( string version )
        {
            RepositoryVersion = version;
        }

    }

**Comment by gregsdennis** [comment]
Hey Jim.  Thanks for the report.

That stack trace is really long, which means that the system is running into nested structures.  What's in `DeploymentItem`?  If you comment out that property, does it work?

**Comment by kampilan** [comment]
Sorry forgot to include DeploymentUnit
I will try and comment out and see if that works. Just to highlight: it works fine with 2.0.1

Thanks so much
Jim


    public class DeploymentUnit
    {


        [JsonIgnore] 
        public string Uid { get; set; } = Base62Converter.NewGuid();

        [Required]
        public string Name { get; set; } = "";

        [Required]
        public string Alias { get; set; } = "";

        [Required]
        public string Build { get; set; } = "";

        [Required]
        public string Checksum { get; set; } = "";

        [Required]
        public string Assembly { get; set; } = "";

        [Required]
        public bool Deploy { get; set; }

        [Required]
        public bool WaitForStart { get; set; }

        [Required]
        public bool ShowWindow { get; set; }

        [Required]
        public JsonObject Configuration { get; set; } = new JsonObject();


        [JsonIgnore]
        public Dictionary<string, object> MissionConfiguration { get; } = new Dictionary<string, object>();


        [JsonIgnore]
        public string RepositoryLocation { get; set; } = "";


        [JsonIgnore]
        public MemoryStream RepositoryContent { get; } = new MemoryStream();


        [JsonIgnore]
        public string InstallationLocation { get; set; } = "";

        [JsonIgnore]
        public string UnitConfigLocation { get; set; } = "";

        [JsonIgnore]
        public string MissionConfigLocation { get; set; } = "";

        [JsonIgnore]
        public string ExecutionCommand { get; set; } = "";

        [JsonIgnore]
        public string ExecutionArguments { get; set; } = "";


        [JsonIgnore]
        public bool HasLoaded { get; set; }


        [JsonIgnore]
        public bool HasInstalled { get; set; }


    }

**Comment by gregsdennis** [comment]
So it looks like it's the `JsonObject` that's causing the problem.  I suggest changing your refiner to a generator.  All it should need to do is add a new `TypeIntent` (instead of looking for one that already exists).

I'll continue to look into what's causing the exception.

---

Also, for future requests, please try to isolate a minimally reproducible example.  It helps identify the issue.
