### ISSUE TITLE
Validating an object that defines properties with `DateTimeOffset` values throws an `ArgumentOutOfRangeException`

### ISSUE THREAD

**Issue by cdavernas** [gregsdennis/json-everything#354]
**Environment**
- Nuget Package: JsonSchema.Net
- Nuget Version: 3.0.0.0
- OS: Windows 11
- .Net Target: NET CORE 7.0

**Describe the bug**

Validating an object that defines properties with `DateTimeOffset` values throws an `ArgumentOutOfRangeException`: 'Specified argument was out of the range of valid values. (Parameter 'node')'

Stacktrace:

```
   at Json.Schema.JsonNodeExtensions.GetSchemaValueType(JsonNode node)
   at Json.Schema.TypeKeyword.Validate(ValidationContext context)
   at Json.Schema.JsonSchema.ValidateSubschema(ValidationContext context)
   at Json.Schema.PropertiesKeyword.Validate(ValidationContext context)
   at Json.Schema.JsonSchema.ValidateSubschema(ValidationContext context)
   at Json.Schema.PropertiesKeyword.Validate(ValidationContext context)
   at Json.Schema.JsonSchema.ValidateSubschema(ValidationContext context)
   at Json.Schema.JsonSchema.Validate(JsonNode root, ValidationOptions options)
   at Synapse.Api.Services.ResourceAdmissionControl.<>c__DisplayClass13_0.<ValidateResourceSchemaAsync>b__0() in [REDACTED]/ResourceAdmissionControl.cs:line 144
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
```

**To Reproduce**

Try to validate the following object, using the following schema:

```yaml
$id: https://serverlessworkflow.io/schemas/0.8/workflow.json
$schema: http://json-schema.org/draft-07/schema
description: Serverless Workflow specification - workflow schema
type: object
properties:
  apiVersion:
    type: string
    minLength: 2
  kind:
    type: string
    minLength: 3
  metadata:
    type: object
    properties:
      id:
        type: string
        minLength: 10
      name:
        type: string
        minlength: 3
      namePrefix:
        type: string
        minLength: 3
      namespace:
        type: string
        minLength: 3
      createdAt:
        type: string
      lastModified:
        type: string
      specVersion:
        type: number
        minValue: 0
      statusVersion:
        type: number
        minValue: 0
      dataVersion:
        type: number
        minValue: 0
    required:
      - id
      - name
      - createdAt
      - lastModified
additionalProperties: false
required:
  - apiVersion
  - kind
  - metadata
```

Object to validate:
```yaml
apiVersion: core.synapse-wfms.io/v1
kind: ResourceDefinition
metadata:
  name: webhook
  id: 30a57bef-6c55-4051-bf7e-21b274d1b280
  createdAt: '2022-12-11T21:50:47.9588474+00:00'
  lastModified: '2022-12-11T21:50:47.9599765+00:00'
spec:
  names:
    kind: Webhook
    singular: webhook
    plural: webhooks
    shortNames:
    - wh
  group: core.synapse-wfms.io
  version: v1
  scope: global
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      type: object
      properties:
        spec:
          type: object
      required:
      - spec
  conversion:
    strategy: webhook
    webhook:
      uri: https://test.com
```

**Expected behavior**

The schema to properly validate the resource

**Comment by gregsdennis** [comment]
Hey there.  Thanks for the report.

I don't think this is an issue with the validator, though, since you're not actually validating the format of the date-times.  Since there's no format validation, there nowhere that `2022-12-11T21:50:47.9588474+00:00` would be parsed as a date.  I think your problem is somewhere else.  Are you trying to deserialize this into a model?

Secondly, the `$schema` value should be `http://json-schema.org/draft-07/schema#` (with the `#`).  (I know it shouldn't make a difference, but it does.)

**Comment by gregsdennis** [comment]
Do you think you can replicate the issue in a minimal schema/instance?

**Comment by cdavernas** [comment]
@gregsdennis I'll have a look asap, will let you know if I can repro on my work station (bug was on my laptop, so who knows?) after the `$schema` fix and after upgrading to 3.3.2.

**Comment by gregsdennis** [comment]
This is the output I get when running under 3.3.2:

```json
{
  "valid": false,
  "keywordLocation": "#/additionalProperties",
  "instanceLocation": "#/spec",
  "error": "All values fail against the false schema"
}
```

In your code above

```c#
var defaultSchemaJson = V1Resource.DefaultSchema.ToJsonDocument().RootElement.AsNode()!.AsObject()!;
var resourceSchemaJson = version.Schema.ToJsonDocument().RootElement.AsNode()!.AsObject()!;
```

What are `V1Resource.DefaultSchema` and `version`?  If these are objects, and you're just wanting them to be `JsonNode`, I suggest simply serializing them with `JsonSerializer.SerializeToNode()`.

**Comment by cdavernas** [comment]
I fail to repro the issues with aforementioned fixes.
|  I suggest simply serializing them with JsonSerializer.SerializeToNode().
Noted! Will do, cheers, didn't know about that extension
