### ISSUE TITLE
InvalidOperationException is thrown while patching elements in array

### ISSUE THREAD

**Issue by anarujnii** [gregsdennis/json-everything#393]
**Environment**
- Nuget Package: JsonPatch.Net
- Nuget Version: 2.0.4
- OS: Windows 11 Pro 
- .Net Target: .NET 5, 6, 7

**Describe the bug**
`InvalidOperationException` is thrown when I try to patch JSON object from a JSON array.
Exception message: `The node already has a parent.`
See call stack below.

**To Reproduce**

- Parse JSON array
- Pick one object and try to patch it
- Get an error

<details><summary>Code to reproduce the problem</summary>
<p>

```
using System;
using System.Linq;
using System.Text.Json;
using System.Text.Json.Nodes;
using Json.More;
using Json.Patch;
using Json.Pointer;

const string mask = "*****";
var maskJson = JsonValue.Create(mask);

var pathsToPatch = new[] { "/first_name", "/last_name" };

var patchOperations = pathsToPatch.Select(path => PatchOperation.Replace(JsonPointer.Parse(path), maskJson));
var patchConfig = new JsonPatch(patchOperations);

const string singleObjectJson = "{" +
    "\"_id\":\"640729d45434f90313d25c78\"," +
    "\"guid\":\"f2e2767c-03e0-4862-addc-7d46c55efb33\"," +
    "\"first_name\":\"Kathrine\"," +
    "\"last_name\":\"Pate\"" +
    "}";

var singleObject = JsonDocument.Parse(singleObjectJson).RootElement;
var patchedSingleObject = patchConfig.Apply(singleObject.AsNode()).Result;
Console.WriteLine(JsonSerializer.Serialize(patchedSingleObject));

const string arrayObjectJson = "[" +
    "{" +
    "\"_id\":\"640729d45434f90313d25c78\"," +
    "\"guid\":\"f2e2767c-03e0-4862-addc-7d46c55efb33\"," +
    "\"first_name\":\"Kathrine\"," +
    "\"last_name\":\"Pate\"" +
    "}," +
    "{\"_id\":\"640729d45b5824ffcabc30a5\"," +
    "\"guid\":\"73193eda-074b-4f31-9f09-507a008ccb75\"," +
    "\"first_name\":\"Rivers\"," +
    "\"last_name\":\"Smith\"" +
    "}" +
    "]";

var arrayObject = JsonDocument.Parse(arrayObjectJson).RootElement;

// Way 1: patch whole array
var patchedArray = patchConfig.Apply(arrayObject.AsNode()).Result;  // <- does nothing

var jsonArray = arrayObject.AsNode().AsArray();

// Way 2: just patch every element
foreach (var element in jsonArray)
{
    var patchedNode = patchConfig.Apply(element).Result;            // <-  throws an error
}

// Way 3: remove from initial array and then patch
for (int currentIndex = jsonArray.Count - 1; currentIndex >= 0; currentIndex--)
{
    var nodeToPatch = jsonArray[currentIndex];
    jsonArray.RemoveAt(currentIndex);

    var patchedNode = patchConfig.Apply(nodeToPatch).Result;        // <-  throws an error
}
```
</p>
</details>

**Expected behavior**
JSON object is patched successfully.

**Additional context**
- Patching of a single object works fine
- Patching of array as a whole does nothing (see Way 1 in code above)
- It looks like removing the object from JSON array resets its parent (see Way 3), but it doesn't work either.

<details><summary>Call stack</summary>
<p>

```
   System.InvalidOperationException: The node already has a parent.
   at System.Text.Json.ThrowHelper.ThrowInvalidOperationException_NodeAlreadyHasParent()
   at System.Text.Json.Nodes.JsonNode.AssignParent(JsonNode parent)
   at System.Text.Json.Nodes.JsonObject.<>c__DisplayClass9_0.<SetItem>b__0()
   at System.Text.Json.JsonPropertyDictionary`1.SetValue(String propertyName, T value, Action assignParent)
   at System.Text.Json.Nodes.JsonObject.SetItem(String propertyName, JsonNode value)
   at System.Text.Json.Nodes.JsonNode.set_Item(String propertyName, JsonNode value)
   at Json.Patch.ReplaceOperationHandler.Process(PatchContext context, PatchOperation operation)
   at Json.Patch.PatchOperation.Handle(PatchContext context)
   at Json.Patch.JsonPatch.Apply(JsonNode source)
   at Program.<Main>$(String[] args) in C:\upteam\Experiments\JsonPatchNetBug\Program.cs:line 48
```

</p>
</details>

**Comment by gregsdennis** [comment]
Thanks for reporting this.  Yeah, it seems I have several places across the libs where I just assign a pre-existing node instead of copying it.

This should be a simple fix.

**Comment by gregsdennis** [comment]
Lastly, just a suggestion.

Instead of 

```c#
var singleObject = JsonDocument.Parse(singleObjectJson).RootElement;
var patchedSingleObject = patchConfig.Apply(singleObject.AsNode()).Result;
```

Just use `JsonNode.Parse()`:

```c#
var singleObject = JsonNode.Parse(singleObjectJson);
var patchedSingleObject = patchConfig.Apply(singleObject).Result;
```
