### ISSUE TITLE
Cannot resolve 2nd level of local $ref.

### ISSUE THREAD

**Issue by lennver** [gregsdennis/json-everything#419]
**Environment**
- Nuget Package: JsonSchema.Net
- Nuget Version: 4.0.0
- OS: Windows 10
- .Net Target: 7

**Describe the bug**
When adding a $ref inside a file that itself is a referenced file the grandhild schema fails to be resolved.

**To Reproduce**
See the attached files, or:
Create a schema with a @ref to another schema, that has a @ref to the yet another schema. Then evaluate it against a json file that follows the schema.

**Expected behavior**
It throws a JsonSchemaException "Cannot resolve base schema from `https://json-everything.net/level2.json`" where level2.json is the grandchild.

`at Json.Schema.RefKeyword.Evaluate(EvaluationContext context)
   at Json.Schema.EvaluationContext.Evaluate()
   at Json.Schema.PropertiesKeyword.Evaluate(EvaluationContext context)
   at Json.Schema.EvaluationContext.Evaluate()
   at Json.Schema.RefKeyword.Evaluate(EvaluationContext context)
   at Json.Schema.EvaluationContext.Evaluate()
   at Json.Schema.PropertiesKeyword.Evaluate(EvaluationContext context)
   at Json.Schema.EvaluationContext.Evaluate()
   at Json.Schema.JsonSchema.Evaluate(JsonNode root, EvaluationOptions options)
   at Json.Schema.JsonSchemaExtensions.Evaluate(JsonSchema jsonSchema, JsonElement jsonElement, EvaluationOptions options)
   at Json.Schema.JsonSchemaExtensions.Evaluate(JsonSchema jsonSchema, JsonDocument jsonDocument, EvaluationOptions options)
   at UserQuery.Main(), line 14`

**Additional context**

[issueExample.zip](https://github.com/gregsdennis/json-everything/files/11085649/issueExample.zip)

**Comment by gregsdennis** [comment]
I think you have actually just provided reproduction for #415.
