### ISSUE TITLE
exclusiveMinimum and exclusiveMaximum are booleans in draft-4

### ISSUE THREAD

**Issue by SGStino** [gregsdennis/json-everything#497]
### Nuget Package

JsonSchema.Net

### Package Version

any

### Operating System

None

### .Net Target (if relevant, please specify the version in the description)

None

### A clear and concise description of the bug

exclusiveMinimum and exclusiveMaximum are booleans in draft-4, but JsonSchema expects to read number tokens.

 ```
 Expected number
   at Json.Schema.ExclusiveMinimumKeywordJsonConverter.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCoreAsObject(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](Utf8JsonReader& reader, JsonTypeInfo jsonTypeInfo, ReadStack& state)
   at System.Text.Json.JsonSerializer.Read[TValue](Utf8JsonReader& reader, JsonTypeInfo jsonTypeInfo)
   at Json.Schema.SchemaJsonConverter.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
   at Json.Schema.JsonSchema.FromText(String jsonText, JsonSerializerOptions options)
   at Program.<Main>$(String[] args) in :line 5
  
   ```

### Please add test code or steps to reproduce the behavior

```
var schema = JsonSchema.FromText("{\"$schema\":\"https://json-schema.org/draft-04/schema\", \"type\":\"number\", \"minimum\":0, \"exclusiveMinimum\": true}");
```

### What did you expect?

Either to accept it, ignore it, or automatically convert it to the new specifcation on import?

### Is there any other information you'd like to share regarding this bug?

Currently, the kubernetes uses OpenAPI V3 as schema, that, in this aspect at least, matches json schema draft 4, with exclusiveMinimum/Maximum as booleans, always present as soon as a minimum or maximum is provided.
This means that this library can't be used to parse and handle the OpenAPI V3 schema if it contains these ranges. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gregsdennis** [comment]
Have you read the readme or the documentation?  This project supports draft 6 and after.  There are no plans to support draft 4 as it's part of an older era of JSON Schema.

I do have an open PR with OpenAPI.Net to have them transition to using this library.  The progress on that is slow, but they will continue to support OpenAPI v3.0.  I don't know the likelihood of that being adopted.

**Comment by gregsdennis** [comment]
> Either to accept it, ignore it, or automatically convert it to the new specifcation on import?

You may be able to create a new `JsonConverter` for the keywords and use that deserialize the schema.  This isn't something I'm going to provide out off the box, though.

**Comment by SGStino** [comment]
I just noticed https://github.com/gregsdennis/json-everything/tree/master/JsonSchema.OpenApi, so somehow there should be support for it, but probably need to reference it?

**Comment by gregsdennis** [comment]
That library really only extends 2020-12 for the OpenAPI 3.1 stuff.  It's not going to help this scenario.

**Comment by SGStino** [comment]
Damd K8S, time to upgrade 😢, but considering how long they took to get 3.0 in GA..

I see why they changed the spec though, to get rid of the inter-keyword dependency... 

Editing the converter would require access to the minimum keyword, which might or might not have been parsed yet. 
So i'd need to find a converter at the schema level, not the keyword level and hijack the keyword. 

Or gain access to the SchemaKeywordRegistry, but that is sadly not scoped to specific JsonSerializerOptions?

So i'm guessing my cleanest best bet is to pre-process the schema (in JsonNodes?) and then feed those into a JsonSerializer?

**Comment by gregsdennis** [comment]
> So i'm guessing my cleanest best bet is to pre-process the schema (in JsonNodes?) and then feed those into a JsonSerializer?

Yes, that's also a pretty good option.

Another option, though I don't know how difficult this would be to implement from .Net, would be to use the [alterschema](https://alterschema.sourcemeta.com/) tool.  I believe there's a command line interface, but you'd have to do some work to get that running.

**Comment by gregsdennis** [comment]
If you want, you can steal the draft 4 keyword implemenations I have in https://github.com/gregsdennis/Graeae.  However, they're not something that I'll be adding to this library.
