### ISSUE TITLE
IndexOutOfRangeException occurred  when evaluating schema with parallel execution.

### ISSUE THREAD

**Issue by filzrev** [gregsdennis/json-everything#726]
### Nuget Package

JsonSchema.Net

### Package Version

7.0.0.3

### Operating System

Windows

### .Net Target (if relevant, please specify the version in the description)

.Net (5 or after)

### A clear and concise description of the bug.

`IndexOutOfRangeException` occurred when evaluating JsonSchema with parallel execution.

It's occurred when running [docfx](https://github.com/dotnet/docfx)  CI build with very rare rate.
And following logs are recorded.

```
C:\Projects\GitHub\docfx\docs\extensions\tools.yml: error InvalidInputFile: Unable to load file 'extensions/tools.yml' via processor 'Dashboard': System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.set_Item(TKey key, TValue value)
   at Json.Schema.CommonJsonPointers.GetNumberSegment(Int32 i)
   at Json.Schema.ItemsKeyword.LocateInstances(KeywordEvaluation evaluation)+MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at Json.Schema.KeywordConstraint.BuildEvaluation(SchemaEvaluation schemaEvaluation, JsonPointer instanceLocation, JsonPointer evaluationPath)
   at Json.Schema.SchemaConstraint.BuildEvaluation(JsonNode localInstance, JsonPointer instanceLocation, JsonPointer evaluationPath, EvaluationOptions options)
   at Json.Schema.KeywordConstraint.BuildEvaluation(SchemaEvaluation schemaEvaluation, JsonPointer instanceLocation, JsonPointer evaluationPath)
   at Json.Schema.SchemaConstraint.BuildEvaluation(JsonNode localInstance, JsonPointer instanceLocation, JsonPointer evaluationPath, EvaluationOptions options)
   at Json.Schema.JsonSchema.Evaluate(JsonNode root, EvaluationOptions options)
   at Json.Schema.JsonSchemaExtensions.Evaluate(JsonSchema jsonSchema, JsonElement jsonElement, EvaluationOptions options)
   at Json.Schema.JsonSchemaExtensions.Evaluate(JsonSchema jsonSchema, JsonDocument jsonDocument, EvaluationOptions options)
   at Docfx.Build.SchemaDriven.SchemaValidator.Validate(Object obj) in C:\Projects\GitHub\docfx\src\Docfx.Build.SchemaDriven\Validators\SchemaValidator.cs:line 34
   at Docfx.Build.SchemaDriven.SchemaDrivenDocumentProcessor.Load(FileAndType file, ImmutableDictionary`2 metadata) in C:\Projects\GitHub\docfx\src\Docfx.Build.SchemaDriven\SchemaDrivenDocumentProcessor.cs:line 114
   at Docfx.Build.Engine.HostServiceCreator.Load(IDocumentProcessor processor, ImmutableDictionary`2 metadata, FileMetadata fileMetadata, FileAndType file) in C:\Projects\GitHub\docfx\src\Docfx.Build\HostServiceCreator.cs:line 79
```

From StackTrace logs.
Problem seems to be caused when `Json.Schema.CommonJsonPointers.GetNumberSegment(Int32 i)` method is called from multiple threads simultaneously.

### What did you expect?

`IndexOutOfRangeException` is not occurred.

### Please add test code or steps to reproduce the behavior.

There is no minimum reproducible code is available.

But It can be reproduced with following steps

1. Clone latest docfx repository content. 
2. Run `dotnet build`. 
3. Run` docfx build docs/docfx.json` command until error is occurred.

**Example `pwsh` scripts to run docfx build command**

```pwsh
foreach($i in 1..1000) {
  C:\Projects\GitHub\docfx\src\docfx\bin\Debug\net8.0\docfx.exe build doc/docfx.json
  if($LastExitCode -ne 0) { return }
}
```

### Is there any other information you'd like to share regarding this bug?

As far as I've confirmed. 

`JsonSchema` and `EvaluationOptions` instance is created on initialization.
And only schema evaluation is executed in parallel context.

https://github.com/dotnet/docfx/blob/e9736e826a65bea234cdd8793674b53d480e891a/src/Docfx.Build.SchemaDriven/Validators/SchemaValidator.cs#L34

### Code of Conduct & Contributor Guidelines

- [X] I agree to follow this project's Code of Conduct and Contribution Guidelines.

**Comment by gregsdennis** [comment]
Thanks for the report. I made everything else a concurrent dictionary. Looks like I missed this one.
