### ISSUE TITLE
`Json.Schema.JsonSchema.Evaluate` throws "`System.OverflowException`: Value was either too large or too small for a Decimal."

### ISSUE THREAD

**Issue by vmelamed** [gregsdennis/json-everything#748]
### What's your idea or question?

Here is part of the schema that I am trying to validate agains:
```json
        "doubleConstant": {
            "title": "Double precision, floating point numerical value",
            "type": "object",
            "properties": {
                "double": {
                    "oneOf": [
                        { "type": "number" },
                        {
                            "type": "string",
                            "pattern": "^(?:NaN)|(?:-?Infinity)$"
                        }
                    ]
                }
            },
            "additionalProperties": { "type": "string" },
            "required": [ "double" ]
        },
```
Generally, it works OK. However, when I run unit tests with the C# `double`-s `double.MinValue` or `double.MaxValue`, my program generates the following (partial) JSON: `"double": -1.7976931348623157E+308` and yet the JSON schema validation throws `OverflowException`. Here is the call stack:
```text
Did not expect any exception because the ACTUAL document from 0016 :  should be valid according to the schema `urn:schemas-vm-com:Linq.Expressions.Serialization.Json`., but found System.OverflowException: Value was either too large or too small for a Decimal.
   at System.Number.ThrowOverflowException(String message)
   at System.Decimal.DecCalc.VarDecFromR8(Double input, DecCalc& result)
   at System.Decimal.op_Explicit(Double value)
   at Json.More.JsonNodeExtensions.GetNumber(JsonValue value)
   at Json.Schema.TypeKeyword.Evaluator(KeywordEvaluation evaluation, EvaluationContext context, SchemaValueType expectedType)
   at Json.Schema.TypeKeyword.<GetConstraint>b__7_0(KeywordEvaluation e, EvaluationContext c)
   at Json.Schema.KeywordEvaluation.Evaluate(EvaluationContext context)
   at Json.Schema.SchemaEvaluation.Evaluate(EvaluationContext context)
   at Json.Schema.KeywordEvaluation.Evaluate(EvaluationContext context)
   at Json.Schema.SchemaEvaluation.Evaluate(EvaluationContext context)
   at Json.Schema.KeywordEvaluation.Evaluate(EvaluationContext context)
   at Json.Schema.SchemaEvaluation.Evaluate(EvaluationContext context)
   at Json.Schema.KeywordEvaluation.Evaluate(EvaluationContext context)
   at Json.Schema.SchemaEvaluation.Evaluate(EvaluationContext context)
   at Json.Schema.KeywordEvaluation.Evaluate(EvaluationContext context)
   at Json.Schema.SchemaEvaluation.Evaluate(EvaluationContext context)
   at Json.Schema.KeywordEvaluation.Evaluate(EvaluationContext context)
   at Json.Schema.SchemaEvaluation.Evaluate(EvaluationContext context)
   at Json.Schema.KeywordEvaluation.Evaluate(EvaluationContext context)
   at Json.Schema.SchemaEvaluation.Evaluate(EvaluationContext context)
   at Json.Schema.JsonSchema.Evaluate(JsonNode root, EvaluationOptions options)
```
At the moment I suspect the call `Json.More.JsonNodeExtensions.GetNumber(JsonValue value)` invoking the explicit cast of `double` to `decimal`. Note that unit tests with small absolute value numbers like `-2.234567891233658E-123` and `5.1234567891234567E-123` pass. And even stranger: tests with `(double)float.MinValue` (-3.4028234663852886E+38) and `(double)float.MaxValue` (3.4028234663852886E+38) fail with the same exception. 

Am I doing something wrong?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gregsdennis** [comment]
Hey there. Please refer to #747.

I'll update the documentation, as I notice it's not there.

**Comment by gregsdennis** [comment]
I've pushed an edit to the docs, but do have a look at that other issue.  It has an explanation as to why I went with `decimal` and a workaround if you're hard-stuck on `double`.

**Comment by vmelamed** [comment]
I get it. My problem is that I am writing a gen. purpose library, so I do not own the types that I de/serialize and cannot choose whether to use `double`, `float`, or `decimal` so I try to preserve the fidelity of the C# types whatever they may be. That of course runs into the above problem. I understand your dilemma, though - it all comes from the crappy type system of JavaScript. On top of all that: how do you deal with "integer"-s above 2^53, sigh... Thank you very much for the prompt response! I'll think about implementing your suggestion in my code.

**Comment by gregsdennis** [comment]
@vmelamed in the other issue, I've suggested a workaround that might help.
